### ISSUE TITLE
Multiple R&D access shows cards in wrong order

### ISSUE THREAD

**Issue by cpjolicoeur** [mrroach/CentralServer#17]
If accessing multiple cards from R&D (with a card like medium), the cards are accessed in reverse order. 

If I access a single Card1 on a run, and then get a toke and make an immediate run again to access 2 cards, I would expect to access Card1 again first and then Card2, instead I am shown Card2 first and then Card1.  If i run again, I see Card3 then Card2 then Card1 instead of Card1, Card2, Card3.

**Comment by mrroach** [comment]
Fixed in db6535c
