### ISSUE TITLE
Trashing a card in server doesnt remove that card or server

### ISSUE THREAD

**Issue by cpjolicoeur** [mrroach/CentralServer#19]
There are cases where the runner can run on an unprotected remote server with just a Melange, for instance, and trash the Melange, but the card still stays in the UI as installed  on both the corp and runner UI even tho it was logged and removed from the game.

The server stays highlighted red like a run is still being made on it: 

[Screenshot](https://www.dropbox.com/s/2a3iwp70fil0mf2/Screenshot%202014-02-07%2017.20.54.png)

The server will only go away on a refresh.

**Comment by mrroach** [comment]
Ah, I see what's happening there. The run is (incorrectly) getting cancelled because the server stops existing, and I don't think the UI handles servers ceasing to exist properly.

**Comment by mrroach** [comment]
Fixed in 274e647
