### ISSUE TITLE
Implement card 01031 (trade an agenda for money)

### ISSUE THREAD

**Issue by mrroach** [mrroach/CentralServer#31]
Because this card will be used all the time? :-)

**Comment by cpjolicoeur** [comment]
We should put stat tracking into the app to see if this card ever gets used once.  And give some kind of prize to the first person who actually does.

Can be an easter-egg :)

**Comment by mrroach** [comment]
I am amazed to report that I had someone use this on OCTGN last night. Who would have thought? :-)

**Comment by mrroach** [comment]
Implemented in 893fec53e984deff58622519d973ee7619355a7b
