### ISSUE TITLE
Renumber Card Sets based on image IDs

### ISSUE THREAD

**Issue by cpjolicoeur** [mrroach/CentralServer#7]
Is there any reason the card sets are numbered 0-3 instead of 1-4?

The image sequences are all in the format of 01003 but we currently index the card sets 00-03, so card image 02003 actually applies to card 01003.

This is a bit confusing at times and seems like maybe we could keep consistent and number the cards and images in a similar order with Core starting at 01 instead of 00

**Comment by mrroach** [comment]
Heh, yeah, I realized that after my rename. Yes, this should happen.

**Comment by cpjolicoeur** [comment]
KK, I assumed so.  I can probably make this happen and send a pull request for it.  I'm working on the localization file for the names anyways at the moment so its kind of related.

**Comment by cpjolicoeur** [comment]
PR #12 should fix this
