### ISSUE TITLE
Need to be able to perform multiple actions during trigger windows

### ISSUE THREAD

**Issue by cpjolicoeur** [mrroach/CentralServer#9]
For example, currently a player can only rez a single card during a trigger window (runner end of turn for instance).  Should be able to perform multiple actions in each window if multiple actions are avaiable (rez multiple PAD Campaings, etc....)

**Comment by mrroach** [comment]
Hm. That must be a recent bug in the timing_phase code.

**Comment by cpjolicoeur** [comment]
Well, let me test some more then.  I'll look into it.  I know the last few passes when I've rezzed a card the action window has immediately flipped back to the runner, but I guess it could be something I had done

**Comment by mrroach** [comment]
Just verified that I could rez multiple cards until I either ran out or chose "Do nothing." Going to optimistically close this out, but if you find a reproducible example, go ahead and reopen.
